import type { BoardErrorCodeV2 } from '../src/index.js';

export type FixtureParserName =
  | 'ArtifactManifestParserV1'
  | 'ArtifactReferenceParserV1'
  | 'ArtifactResourceParserV1'
  | 'ArtifactRuntimeSummaryParserV1'
  | 'BoardCapabilitiesParserV1'
  | 'BoardDocumentParserV2'
  | 'BoardErrorParserV1'
  | 'BoardEventEnvelopeParserV1'
  | 'BoardNodeParserV1'
  | 'BoardOperationEnvelopeParserV1'
  | 'BoardOperationRequestParserV1'
  | 'BoardOperationResultParserV1'
  | 'BoardSnapshotParserV1'
  | 'CanonicalJsonParserV1'
  | 'HitlInteractionParserV1'
  | 'HitlRequestDefinitionParserV1'
  | 'HitlResponseParserV1'
  | 'MutationEnvelopeParserV1'
  | 'MutationRequestParserV1'
  | 'MutationResultParserV1'
  | 'SceneParserV1';

export type FixtureCatalogEntry =
  | { kind: 'valid'; path: string; schema: FixtureParserName }
  | { kind: 'scenario'; path: string; evaluator: string; expectedRelation: string }
  | {
      kind: 'invalid';
      path: string;
      schema: FixtureParserName;
      expectedErrorCode: BoardErrorCodeV2;
      expectedPath: Array<string | number> | null;
      expectedDetails: unknown;
    };

export const FIXTURE_CATALOG = [
  { kind: 'valid', path: 'valid/artifact-manifest.v1.json', schema: 'ArtifactManifestParserV1' },
  { kind: 'valid', path: 'valid/artifact-reference.v1.json', schema: 'ArtifactReferenceParserV1' },
  { kind: 'valid', path: 'valid/artifact-resource.v1.json', schema: 'ArtifactResourceParserV1' },
  {
    kind: 'valid',
    path: 'valid/artifact-runtime-summary-ready.v1.json',
    schema: 'ArtifactRuntimeSummaryParserV1',
  },
  { kind: 'valid', path: 'valid/board-node-markdown.v1.json', schema: 'BoardNodeParserV1' },
  {
    kind: 'valid',
    path: 'valid/capabilities-default.v1.json',
    schema: 'BoardCapabilitiesParserV1',
  },
  { kind: 'valid', path: 'valid/error-artifact-not-found.v1.json', schema: 'BoardErrorParserV1' },
  {
    kind: 'valid',
    path: 'valid/error-board-already-archived.v1.json',
    schema: 'BoardErrorParserV1',
  },
  { kind: 'valid', path: 'valid/error-board-not-found.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-capability-denied.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-duplicate-node-id.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-forbidden.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-hitl-request-expired.v1.json', schema: 'BoardErrorParserV1' },
  {
    kind: 'valid',
    path: 'valid/error-hitl-request-id-conflict.v1.json',
    schema: 'BoardErrorParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/error-hitl-request-not-found.v1.json',
    schema: 'BoardErrorParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/error-hitl-response-conflict.v1.json',
    schema: 'BoardErrorParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/error-idempotency-key-reused.v1.json',
    schema: 'BoardErrorParserV1',
  },
  { kind: 'valid', path: 'valid/error-internal.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-invalid-layout.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-invalid-payload.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-limit-exceeded.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-payload-too-large.v1.json', schema: 'BoardErrorParserV1' },
  {
    kind: 'valid',
    path: 'valid/error-protocol-version-mismatch.v1.json',
    schema: 'BoardErrorParserV1',
  },
  { kind: 'valid', path: 'valid/error-rate-limited.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-revision-conflict.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-revision-not-found.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-service-unavailable.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-unauthenticated.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-unknown-command-type.v1.json', schema: 'BoardErrorParserV1' },
  { kind: 'valid', path: 'valid/error-unknown-node-type.v1.json', schema: 'BoardErrorParserV1' },
  {
    kind: 'valid',
    path: 'valid/error-unknown-operation-type.v1.json',
    schema: 'BoardErrorParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/event-artifact-status-changed.v1.json',
    schema: 'BoardEventEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/event-board-snapshot.v1.json',
    schema: 'BoardEventEnvelopeParserV1',
  },
  { kind: 'valid', path: 'valid/event-hitl-updated.v1.json', schema: 'BoardEventEnvelopeParserV1' },
  {
    kind: 'valid',
    path: 'valid/event-presence-updated.v1.json',
    schema: 'BoardEventEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/event-revision-created.v1.json',
    schema: 'BoardEventEnvelopeParserV1',
  },
  { kind: 'valid', path: 'valid/event-stream-error.v1.json', schema: 'BoardEventEnvelopeParserV1' },
  {
    kind: 'valid',
    path: 'valid/event-stream-heartbeat.v1.json',
    schema: 'BoardEventEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/event-stream-resync-required.v1.json',
    schema: 'BoardEventEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/hitl-interaction-answered.v1.json',
    schema: 'HitlInteractionParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/hitl-interaction-cancelled.v1.json',
    schema: 'HitlInteractionParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/hitl-interaction-expired.v1.json',
    schema: 'HitlInteractionParserV1',
  },
  { kind: 'valid', path: 'valid/hitl-interaction-open.v1.json', schema: 'HitlInteractionParserV1' },
  {
    kind: 'valid',
    path: 'valid/hitl-interaction-superseded.v1.json',
    schema: 'HitlInteractionParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/hitl-request-choice.v1.json',
    schema: 'HitlRequestDefinitionParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/hitl-request-confirmation.v1.json',
    schema: 'HitlRequestDefinitionParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/hitl-request-form.v1.json',
    schema: 'HitlRequestDefinitionParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/hitl-request-info.v1.json',
    schema: 'HitlRequestDefinitionParserV1',
  },
  { kind: 'valid', path: 'valid/hitl-response-choice.v1.json', schema: 'HitlResponseParserV1' },
  {
    kind: 'valid',
    path: 'valid/hitl-response-confirmation.v1.json',
    schema: 'HitlResponseParserV1',
  },
  { kind: 'valid', path: 'valid/hitl-response-form.v1.json', schema: 'HitlResponseParserV1' },
  { kind: 'valid', path: 'valid/hitl-response-info.v1.json', schema: 'HitlResponseParserV1' },
  {
    kind: 'valid',
    path: 'valid/mutation-envelope-artifact-publish.v1.json',
    schema: 'MutationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-envelope-artifact-stop.v1.json',
    schema: 'MutationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-envelope-hitl-request.v1.json',
    schema: 'MutationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-envelope-hitl-respond.v1.json',
    schema: 'MutationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-envelope-scene-clear.v1.json',
    schema: 'MutationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-envelope-scene-replace.v1.json',
    schema: 'MutationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-envelope-scene-restore.v1.json',
    schema: 'MutationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-request-artifact-publish.v1.json',
    schema: 'MutationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-request-artifact-stop.v1.json',
    schema: 'MutationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-request-hitl-request.v1.json',
    schema: 'MutationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-request-hitl-respond.v1.json',
    schema: 'MutationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-request-scene-clear.v1.json',
    schema: 'MutationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-request-scene-replace.v1.json',
    schema: 'MutationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-request-scene-restore.v1.json',
    schema: 'MutationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-result-artifact-publish.v1.json',
    schema: 'MutationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-result-artifact-stop.v1.json',
    schema: 'MutationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-result-hitl-request.v1.json',
    schema: 'MutationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-result-hitl-respond.v1.json',
    schema: 'MutationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-result-scene-clear.v1.json',
    schema: 'MutationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-result-scene-replace.v1.json',
    schema: 'MutationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/mutation-result-scene-restore.v1.json',
    schema: 'MutationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-envelope-artifact-get.v1.json',
    schema: 'BoardOperationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-envelope-board-archive.v1.json',
    schema: 'BoardOperationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-envelope-board-create.v1.json',
    schema: 'BoardOperationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-envelope-board-get.v1.json',
    schema: 'BoardOperationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-envelope-board-list.v1.json',
    schema: 'BoardOperationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-envelope-capabilities-get.v1.json',
    schema: 'BoardOperationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-envelope-history-get.v1.json',
    schema: 'BoardOperationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-envelope-history-list.v1.json',
    schema: 'BoardOperationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-envelope-hitl-read.v1.json',
    schema: 'BoardOperationEnvelopeParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-request-artifact-get.v1.json',
    schema: 'BoardOperationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-request-board-archive.v1.json',
    schema: 'BoardOperationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-request-board-create.v1.json',
    schema: 'BoardOperationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-request-board-get.v1.json',
    schema: 'BoardOperationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-request-board-list.v1.json',
    schema: 'BoardOperationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-request-capabilities-get.v1.json',
    schema: 'BoardOperationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-request-history-get.v1.json',
    schema: 'BoardOperationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-request-history-list.v1.json',
    schema: 'BoardOperationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-request-hitl-read.v1.json',
    schema: 'BoardOperationRequestParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-result-artifact-get.v1.json',
    schema: 'BoardOperationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-result-board-archive.v1.json',
    schema: 'BoardOperationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-result-board-create.v1.json',
    schema: 'BoardOperationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-result-board-get.v1.json',
    schema: 'BoardOperationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-result-board-list.v1.json',
    schema: 'BoardOperationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-result-capabilities-get.v1.json',
    schema: 'BoardOperationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-result-history-get.v1.json',
    schema: 'BoardOperationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-result-history-list.v1.json',
    schema: 'BoardOperationResultParserV1',
  },
  {
    kind: 'valid',
    path: 'valid/operation-result-hitl-read.v1.json',
    schema: 'BoardOperationResultParserV1',
  },
  { kind: 'valid', path: 'valid/scene-all-node-types.v1.json', schema: 'SceneParserV1' },
  { kind: 'valid', path: 'valid/scene-empty.v1.json', schema: 'SceneParserV1' },
  { kind: 'valid', path: 'valid/scene-recursive-layout.v1.json', schema: 'SceneParserV1' },
  { kind: 'valid', path: 'valid/scene-renderer-families.v1.json', schema: 'SceneParserV1' },
  { kind: 'valid', path: 'valid/snapshot-board.v1.json', schema: 'BoardSnapshotParserV1' },
  { kind: 'valid', path: 'valid/document-basic.v2.json', schema: 'BoardDocumentParserV2' },
  {
    kind: 'scenario',
    path: 'scenarios/board-archive-idempotency-replay.v1.json',
    evaluator: 'board-archive-idempotency-replay',
    expectedRelation: 'replay',
  },
  {
    kind: 'scenario',
    path: 'scenarios/board-archive-idempotency-reuse-conflicts.v1.json',
    evaluator: 'board-archive-idempotency-reuse-conflicts',
    expectedRelation: 'conflict',
  },
  {
    kind: 'scenario',
    path: 'scenarios/board-create-idempotency-replay.v1.json',
    evaluator: 'board-create-idempotency-replay',
    expectedRelation: 'replay',
  },
  {
    kind: 'scenario',
    path: 'scenarios/board-create-idempotency-reuse-conflicts.v1.json',
    evaluator: 'board-create-idempotency-reuse-conflicts',
    expectedRelation: 'conflict',
  },
  {
    kind: 'scenario',
    path: 'scenarios/board-create-initial-empty-head.v1.json',
    evaluator: 'board-create-initial-empty-head',
    expectedRelation: 'initial-head',
  },
  {
    kind: 'scenario',
    path: 'scenarios/board-get-initial-snapshot.v1.json',
    evaluator: 'board-get-initial-snapshot',
    expectedRelation: 'same-head',
  },
  {
    kind: 'scenario',
    path: 'scenarios/canonical-unicode-key-order.v1.json',
    evaluator: 'canonical-unicode-key-order',
    expectedRelation: 'canonical-bytes',
  },
  {
    kind: 'scenario',
    path: 'scenarios/compatibility-major-mismatch-bidirectional.v1.json',
    evaluator: 'compatibility-major-mismatch-bidirectional',
    expectedRelation: 'rejected',
  },
  {
    kind: 'scenario',
    path: 'scenarios/compatibility-v1-added-field-rejected.v1.json',
    evaluator: 'compatibility-v1-added-field-rejected',
    expectedRelation: 'rejected',
  },
  {
    kind: 'scenario',
    path: 'scenarios/compatibility-v1-exact.v1.json',
    evaluator: 'compatibility-v1-exact',
    expectedRelation: 'accepted',
  },
  {
    kind: 'scenario',
    path: 'scenarios/first-scene-replace-from-created-head.v1.json',
    evaluator: 'first-scene-replace-from-created-head',
    expectedRelation: 'next-revision',
  },
  {
    kind: 'scenario',
    path: 'scenarios/hitl-placement-reconnect-correlation.v1.json',
    evaluator: 'hitl-placement-reconnect-correlation',
    expectedRelation: 'same-id',
  },
  {
    kind: 'scenario',
    path: 'scenarios/hitl-request-result-outcomes.v1.json',
    evaluator: 'hitl-request-result-outcomes',
    expectedRelation: 'outcome-matrix',
  },
  {
    kind: 'scenario',
    path: 'scenarios/hitl-respond-result-outcomes.v1.json',
    evaluator: 'hitl-respond-result-outcomes',
    expectedRelation: 'outcome-matrix',
  },
  {
    kind: 'scenario',
    path: 'scenarios/hitl-terminal-chronology-boundaries.v1.json',
    evaluator: 'hitl-terminal-chronology-boundaries',
    expectedRelation: 'chronology',
  },
  {
    kind: 'scenario',
    path: 'scenarios/idempotency-changed-expected-revision-conflict.v1.json',
    evaluator: 'idempotency-changed-expected-revision-conflict',
    expectedRelation: 'conflict',
  },
  {
    kind: 'scenario',
    path: 'scenarios/idempotency-changed-grant-conflict.v1.json',
    evaluator: 'idempotency-changed-grant-conflict',
    expectedRelation: 'conflict',
  },
  {
    kind: 'scenario',
    path: 'scenarios/idempotency-changed-payload-conflict.v1.json',
    evaluator: 'idempotency-changed-payload-conflict',
    expectedRelation: 'conflict',
  },
  {
    kind: 'scenario',
    path: 'scenarios/idempotency-changed-scopes-conflict.v1.json',
    evaluator: 'idempotency-changed-scopes-conflict',
    expectedRelation: 'conflict',
  },
  {
    kind: 'scenario',
    path: 'scenarios/idempotency-scopes-reordered-replay.v1.json',
    evaluator: 'idempotency-scopes-reordered-replay',
    expectedRelation: 'replay',
  },
  {
    kind: 'scenario',
    path: 'scenarios/scene-clear-after-create.v1.json',
    evaluator: 'scene-clear-after-create',
    expectedRelation: 'new-checkpoint',
  },
  {
    kind: 'scenario',
    path: 'scenarios/scene-clear-idempotent-replay.v1.json',
    evaluator: 'scene-clear-idempotent-replay',
    expectedRelation: 'replay',
  },
  {
    kind: 'scenario',
    path: 'scenarios/scene-replace-request-id-replay.v1.json',
    evaluator: 'scene-replace-request-id-replay',
    expectedRelation: 'replay',
  },
  {
    kind: 'scenario',
    path: 'scenarios/snapshot-event-reconnect-watermark.v1.json',
    evaluator: 'snapshot-event-reconnect-watermark',
    expectedRelation: 'inclusive-watermark',
  },
  {
    kind: 'invalid',
    path: 'invalid/artifact-resource-path-traversal.v1.json',
    schema: 'ArtifactResourceParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['path'],
    expectedDetails: { path: ['path'], issue: 'artifact path must be normalized' },
  },
  {
    kind: 'invalid',
    path: 'invalid/capabilities-limit-mismatch.v1.json',
    schema: 'BoardCapabilitiesParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['limits', 'maxSceneNodes'],
    expectedDetails: {
      path: ['limits', 'maxSceneNodes'],
      issue: 'Invalid literal value, expected 500',
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/capabilities-missing-catalog-entry.v1.json',
    schema: 'BoardCapabilitiesParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['supported', 'nodeTypes'],
    expectedDetails: {
      path: ['supported', 'nodeTypes'],
      issue: 'Array must contain exactly 15 element(s)',
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/capabilities-unknown-node-type.v1.json',
    schema: 'BoardCapabilitiesParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['supported', 'nodeTypes', 0],
    expectedDetails: {
      path: ['supported', 'nodeTypes', 0],
      issue:
        "Invalid enum value. Expected 'layout.split' | 'layout.grid' | 'layout.tabs' | 'layout.canvas' | 'content.markdown' | 'content.code' | 'content.table' | 'content.chart' | 'content.map' | 'content.drawi",
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/command-unknown-type.v1.json',
    schema: 'MutationRequestParserV1',
    expectedErrorCode: 'UNKNOWN_COMMAND_TYPE',
    expectedPath: ['command', 'type'],
    expectedDetails: { path: ['command', 'type'], receivedType: 'scene.unknown' },
  },
  {
    kind: 'invalid',
    path: 'invalid/document-default-missing.v2.json',
    schema: 'BoardDocumentParserV2',
    expectedErrorCode: 'INVALID_DOCUMENT',
    expectedPath: ['defaultPageId'],
    expectedDetails: { path: ['defaultPageId'], reason: 'default_page_missing' },
  },
  {
    kind: 'invalid',
    path: 'invalid/document-duplicate-page-id.v2.json',
    schema: 'BoardDocumentParserV2',
    expectedErrorCode: 'INVALID_DOCUMENT',
    expectedPath: ['pages', 1, 'pageId'],
    expectedDetails: { path: ['pages', 1, 'pageId'], reason: 'duplicate_page_id' },
  },
  {
    kind: 'invalid',
    path: 'invalid/document-invalid-display-mode.v2.json',
    schema: 'BoardDocumentParserV2',
    expectedErrorCode: 'INVALID_DOCUMENT',
    expectedPath: ['pages', 0, 'displayMode'],
    expectedDetails: {
      path: ['pages', 0, 'displayMode'],
      reason: 'invalid_display_mode',
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/document-unknown-version.v3.json',
    schema: 'BoardDocumentParserV2',
    expectedErrorCode: 'PROTOCOL_VERSION_MISMATCH',
    expectedPath: null,
    expectedDetails: {
      reason: 'schema_revision',
      supportedMajor: 1,
      receivedMajor: 1,
      field: 'document.schemaVersion',
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/error-details-code-mismatch.v1.json',
    schema: 'BoardErrorParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['details'],
    expectedDetails: { path: ['details'], issue: 'Expected null, received object' },
  },
  {
    kind: 'invalid',
    path: 'invalid/error-revision-conflict-null-actual-head.v1.json',
    schema: 'BoardErrorParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['details', 'actualRevisionId'],
    expectedDetails: {
      path: ['details', 'actualRevisionId'],
      issue: 'Expected string, received null',
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/event-resync-null-head.v1.json',
    schema: 'BoardEventEnvelopeParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['data', 'durableHeadRevisionId'],
    expectedDetails: {
      path: ['data', 'durableHeadRevisionId'],
      issue: 'Expected string, received null',
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/event-snapshot-board-id-mismatch.v1.json',
    schema: 'BoardEventEnvelopeParserV1',
    expectedErrorCode: 'INVALID_LAYOUT',
    expectedPath: ['data', 'snapshot', 'boardId'],
    expectedDetails: { path: ['data', 'snapshot', 'boardId'], reason: 'reference' },
  },
  {
    kind: 'invalid',
    path: 'invalid/event-snapshot-sequence-mismatch.v1.json',
    schema: 'BoardEventEnvelopeParserV1',
    expectedErrorCode: 'INVALID_LAYOUT',
    expectedPath: ['data', 'snapshot', 'lastEventSequence'],
    expectedDetails: { path: ['data', 'snapshot', 'lastEventSequence'], reason: 'reference' },
  },
  {
    kind: 'invalid',
    path: 'invalid/event-unknown-type.v1.json',
    schema: 'BoardEventEnvelopeParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['data', 'type'],
    expectedDetails: {
      path: ['data', 'type'],
      issue:
        "Invalid discriminator value. Expected 'board.snapshot' | 'board.revision.created' | 'hitl.updated' | 'artifact.status.changed' | 'presence.updated' | 'stream.resync.required' | 'stream.heartbeat' | 's",
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/hitl-answered-before-created.v1.json',
    schema: 'HitlInteractionParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['answeredAt'],
    expectedDetails: { path: ['answeredAt'], issue: 'answered chronology is invalid' },
  },
  {
    kind: 'invalid',
    path: 'invalid/hitl-duplicate-option-id.v1.json',
    schema: 'HitlRequestDefinitionParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['options'],
    expectedDetails: { path: ['options'], issue: 'option IDs must be unique' },
  },
  {
    kind: 'invalid',
    path: 'invalid/hitl-expired-without-expires-at.v1.json',
    schema: 'HitlInteractionParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['expiresAt'],
    expectedDetails: { path: ['expiresAt'], issue: 'expired chronology is invalid' },
  },
  {
    kind: 'invalid',
    path: 'invalid/hitl-invalid-state.v1.json',
    schema: 'HitlInteractionParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['state'],
    expectedDetails: {
      path: ['state'],
      issue:
        "Invalid enum value. Expected 'open' | 'answered' | 'superseded' | 'expired' | 'cancelled', received 'unknown'",
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/hitl-nonexpired-terminal-at-expiry.v1.json',
    schema: 'HitlInteractionParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['stateUpdatedAt'],
    expectedDetails: { path: ['stateUpdatedAt'], issue: 'terminal chronology is invalid' },
  },
  {
    kind: 'invalid',
    path: 'invalid/hitl-response-scalar-mismatch.v1.json',
    schema: 'HitlInteractionParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['response'],
    expectedDetails: { path: ['response'], issue: 'text field value has wrong type' },
  },
  {
    kind: 'invalid',
    path: 'invalid/json-container-entries-exceeded.v1.json',
    schema: 'CanonicalJsonParserV1',
    expectedErrorCode: 'LIMIT_EXCEEDED',
    expectedPath: [],
    expectedDetails: { limit: 'maxJsonContainerEntries', actual: 10001, maximum: 10000, path: [] },
  },
  {
    kind: 'invalid',
    path: 'invalid/json-depth-exceeded.v1.json',
    schema: 'CanonicalJsonParserV1',
    expectedErrorCode: 'LIMIT_EXCEEDED',
    expectedPath: [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0,
    ],
    expectedDetails: {
      limit: 'maxJsonDepth',
      actual: 65,
      maximum: 64,
      path: [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,
      ],
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/json-lone-surrogate.v1.json',
    schema: 'CanonicalJsonParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: [],
    expectedDetails: { path: [], issue: 'lone surrogate is not allowed' },
  },
  {
    kind: 'invalid',
    path: 'invalid/json-unknown-field.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: [],
    expectedDetails: { path: [], issue: "Unrecognized key(s) in object: 'unknown'" },
  },
  {
    kind: 'invalid',
    path: 'invalid/mutation-envelope-unsorted-scopes.v1.json',
    schema: 'MutationEnvelopeParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['actor', 'scopes'],
    expectedDetails: { path: ['actor', 'scopes'], issue: 'scopes must be sorted and unique' },
  },
  {
    kind: 'invalid',
    path: 'invalid/mutation-request-caller-actor.v1.json',
    schema: 'MutationRequestParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: [],
    expectedDetails: { path: [], issue: "Unrecognized key(s) in object: 'actor'" },
  },
  {
    kind: 'invalid',
    path: 'invalid/mutation-request-idempotency-key-too-long.v1.json',
    schema: 'MutationRequestParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['idempotencyKey'],
    expectedDetails: {
      path: ['idempotencyKey'],
      issue: 'String must contain at most 128 character(s)',
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/mutation-request-missing-expected-revision.v1.json',
    schema: 'MutationRequestParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['expectedRevisionId'],
    expectedDetails: { path: ['expectedRevisionId'], issue: 'Required' },
  },
  {
    kind: 'invalid',
    path: 'invalid/mutation-request-null-expected-revision.v1.json',
    schema: 'MutationRequestParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['expectedRevisionId'],
    expectedDetails: { path: ['expectedRevisionId'], issue: 'Expected string, received null' },
  },
  {
    kind: 'invalid',
    path: 'invalid/mutation-request-restore-missing-source-revision.v1.json',
    schema: 'MutationRequestParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['command', 'sourceRevisionId'],
    expectedDetails: { path: ['command', 'sourceRevisionId'], issue: 'Required' },
  },
  {
    kind: 'invalid',
    path: 'invalid/mutation-result-command-mismatch.v1.json',
    schema: 'MutationResultParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['result', 'revision'],
    expectedDetails: { path: ['result', 'revision'], issue: 'Required' },
  },
  {
    kind: 'invalid',
    path: 'invalid/operation-board-archive-confirm-false.v1.json',
    schema: 'BoardOperationRequestParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['confirm'],
    expectedDetails: { path: ['confirm'], issue: 'Invalid literal value, expected true' },
  },
  {
    kind: 'invalid',
    path: 'invalid/operation-board-create-missing-title.v1.json',
    schema: 'BoardOperationRequestParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['title'],
    expectedDetails: { path: ['title'], issue: 'Required' },
  },
  {
    kind: 'invalid',
    path: 'invalid/operation-result-type-mismatch.v1.json',
    schema: 'BoardOperationResultParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['result', 'snapshot'],
    expectedDetails: { path: ['result', 'snapshot'], issue: 'Required' },
  },
  {
    kind: 'invalid',
    path: 'invalid/operation-unknown-type.v1.json',
    schema: 'BoardOperationRequestParserV1',
    expectedErrorCode: 'UNKNOWN_OPERATION_TYPE',
    expectedPath: ['type'],
    expectedDetails: { path: ['type'], receivedType: 'board.unknown' },
  },
  {
    kind: 'invalid',
    path: 'invalid/protocol-v1-added-field.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: [],
    expectedDetails: { path: [], issue: "Unrecognized key(s) in object: 'extra'" },
  },
  {
    kind: 'invalid',
    path: 'invalid/protocol-version-unsupported-v2.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'PROTOCOL_VERSION_MISMATCH',
    expectedPath: null,
    expectedDetails: {
      reason: 'major',
      supportedMajor: 1,
      receivedMajor: 2,
      field: 'protocolVersion',
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/scene-canvas-extent-exceeded.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'LIMIT_EXCEEDED',
    expectedPath: ['root', 'width'],
    expectedDetails: {
      limit: 'maxCanvasExtent',
      actual: 100001,
      maximum: 100000,
      path: ['root', 'width'],
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/scene-depth-exceeded.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'LIMIT_EXCEEDED',
    expectedPath: [
      'root',
      'tabs',
      0,
      'node',
      'tabs',
      0,
      'node',
      'tabs',
      0,
      'node',
      'tabs',
      0,
      'node',
      'tabs',
      0,
      'node',
      'tabs',
      0,
      'node',
      'tabs',
      0,
      'node',
      'tabs',
      0,
      'node',
      'tabs',
      0,
      'node',
      'tabs',
      0,
      'node',
      'tabs',
      0,
      'node',
      'tabs',
      0,
      'node',
    ],
    expectedDetails: {
      limit: 'maxSceneDepth',
      actual: 13,
      maximum: 12,
      path: [
        'root',
        'tabs',
        0,
        'node',
        'tabs',
        0,
        'node',
        'tabs',
        0,
        'node',
        'tabs',
        0,
        'node',
        'tabs',
        0,
        'node',
        'tabs',
        0,
        'node',
        'tabs',
        0,
        'node',
        'tabs',
        0,
        'node',
        'tabs',
        0,
        'node',
        'tabs',
        0,
        'node',
        'tabs',
        0,
        'node',
        'tabs',
        0,
        'node',
      ],
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/scene-duplicate-node-id.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'DUPLICATE_NODE_ID',
    expectedPath: null,
    expectedDetails: {
      nodeId: 'grid',
      firstPath: ['root', 'children', 0, 'node', 'id'],
      duplicatePath: ['root', 'children', 1, 'node', 'id'],
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/scene-grid-out-of-bounds.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'INVALID_LAYOUT',
    expectedPath: ['root', 'children', 0, 'node', 'children', 1],
    expectedDetails: { path: ['root', 'children', 0, 'node', 'children', 1], reason: 'bounds' },
  },
  {
    kind: 'invalid',
    path: 'invalid/scene-grid-overlap.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'INVALID_LAYOUT',
    expectedPath: ['root', 'children', 0, 'node', 'children', 1],
    expectedDetails: { path: ['root', 'children', 0, 'node', 'children', 1], reason: 'overlap' },
  },
  {
    kind: 'invalid',
    path: 'invalid/scene-image-untrusted-source.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['root', 'source', 'type'],
    expectedDetails: {
      path: ['root', 'source', 'type'],
      issue: 'Invalid literal value, expected "artifact.resource"',
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/scene-node-count-exceeded.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'LIMIT_EXCEEDED',
    expectedPath: ['root'],
    expectedDetails: { limit: 'maxSceneNodes', actual: 502, maximum: 500, path: ['root'] },
  },
  {
    kind: 'invalid',
    path: 'invalid/scene-progress-complete-not-one.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'INVALID_LAYOUT',
    expectedPath: ['root', 'value'],
    expectedDetails: { path: ['root', 'value'], reason: 'bounds' },
  },
  {
    kind: 'invalid',
    path: 'invalid/scene-split-child-limit.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'LIMIT_EXCEEDED',
    expectedPath: ['root', 'children'],
    expectedDetails: {
      limit: 'maxSplitChildren',
      actual: 13,
      maximum: 12,
      path: ['root', 'children'],
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/scene-status-unknown-kind.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['root', 'status'],
    expectedDetails: {
      path: ['root', 'status'],
      issue:
        "Invalid enum value. Expected 'neutral' | 'info' | 'success' | 'warning' | 'error', received 'purple'",
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/scene-tabs-missing-active.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'INVALID_LAYOUT',
    expectedPath: ['root', 'children', 0, 'node', 'children', 0, 'node', 'activeTabId'],
    expectedDetails: {
      path: ['root', 'children', 0, 'node', 'children', 0, 'node', 'activeTabId'],
      reason: 'reference',
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/scene-text-limit-exceeded.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'LIMIT_EXCEEDED',
    expectedPath: ['root', 'markdown'],
    expectedDetails: {
      limit: 'maxMarkdownChars',
      actual: 100001,
      maximum: 100000,
      path: ['root', 'markdown'],
    },
  },
  {
    kind: 'invalid',
    path: 'invalid/scene-unknown-node-type.v1.json',
    schema: 'SceneParserV1',
    expectedErrorCode: 'UNKNOWN_NODE_TYPE',
    expectedPath: ['root', 'type'],
    expectedDetails: { path: ['root', 'type'], receivedType: 'content.unknown' },
  },
  {
    kind: 'invalid',
    path: 'invalid/snapshot-invalid-timestamp.v1.json',
    schema: 'BoardSnapshotParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['revision', 'createdAt'],
    expectedDetails: { path: ['revision', 'createdAt'], issue: 'Invalid' },
  },
  {
    kind: 'invalid',
    path: 'invalid/snapshot-null-head.v1.json',
    schema: 'BoardSnapshotParserV1',
    expectedErrorCode: 'INVALID_PAYLOAD',
    expectedPath: ['revision'],
    expectedDetails: { path: ['revision'], issue: 'Expected object, received null' },
  },
  {
    kind: 'invalid',
    path: 'invalid/snapshot-unresolved-artifact-reference.v1.json',
    schema: 'BoardSnapshotParserV1',
    expectedErrorCode: 'INVALID_LAYOUT',
    expectedPath: ['scene', 'root', 'artifact'],
    expectedDetails: { path: ['scene', 'root', 'artifact'], reason: 'reference' },
  },
  {
    kind: 'invalid',
    path: 'invalid/snapshot-unresolved-hitl-reference.v1.json',
    schema: 'BoardSnapshotParserV1',
    expectedErrorCode: 'INVALID_LAYOUT',
    expectedPath: ['scene', 'root', 'hitlRequestId'],
    expectedDetails: { path: ['scene', 'root', 'hitlRequestId'], reason: 'reference' },
  },
  {
    kind: 'invalid',
    path: 'invalid/snapshot-unresolved-image-artifact-reference.v1.json',
    schema: 'BoardSnapshotParserV1',
    expectedErrorCode: 'INVALID_LAYOUT',
    expectedPath: ['scene', 'root', 'source', 'artifact'],
    expectedDetails: { path: ['scene', 'root', 'source', 'artifact'], reason: 'reference' },
  },
] as const satisfies readonly FixtureCatalogEntry[];
