import { redactSecrets } from '../common/security/redact-secrets.js';

export const AuditEventCatalog = {
  signup_success: 1,
  signup_duplicate: 2,
  login_success: 3,
  login_failure: 4,
  login_rate_limit: 5,
  bcrypt_rehash: 6,
  session_renew: 7,
  session_reuse: 8,
  session_logout: 9,
  session_revoke: 10,
  pairing_create: 11,
  pairing_claim: 12,
  pairing_failure: 13,
  pairing_lock: 14,
  pairing_approve: 15,
  pairing_deny: 16,
  pairing_cancel: 17,
  pairing_expire: 18,
  pairing_redeem: 19,
  grant_issue: 20,
  grant_auth_failure: 21,
  grant_rotate: 22,
  grant_revoke: 23,
  grant_expire: 24,
  capability_denial: 25,
  rate_limiting: 26,
  security_retention_run: 27,
  'hitl.request.created': 28,
  'hitl.response.answered': 29,
  'hitl.request.cancelled': 30,
  'hitl.request.superseded': 31,
  'hitl.request.expired': 32,
  'hitl.response.conflict': 33,
  'artifact.publication.created': 34,
  'artifact.metadata.read': 35,
  'artifact.package.read': 36,
  'artifact.runtime.stopped': 37,
  'artifact.network.denied': 38,
  'artifact.usage.drift': 39,
  'artifact.integrity.failed': 40,
  password_change: 41,
  'invitation.issued': 42,
  'invitation.resent': 43,
  'invitation.revoked': 44,
  'invitation.accepted': 45,
  'membership.role.updated': 46,
  'membership.removed': 47,
  'share.created': 48,
  'share.republished': 49,
  'share.pin.updated': 50,
  'share.update.noop': 51,
  'share.link.rotated': 52,
  'share.revoked': 53,
  'share.archived': 54,
} as const;

export type AuditEventName = keyof typeof AuditEventCatalog;

const MetadataAllowlists: Readonly<Record<AuditEventName, ReadonlySet<string>>> = {
  signup_success: new Set(),
  signup_duplicate: new Set(['reason']),
  login_success: new Set(['workFactorUpgraded']),
  login_failure: new Set(['reason']),
  login_rate_limit: new Set(['bucket']),
  bcrypt_rehash: new Set(['outcome', 'priorCost', 'nextCost']),
  session_renew: new Set(['reason']),
  session_reuse: new Set(['reason', 'detail']),
  session_logout: new Set(['reason']),
  session_revoke: new Set(['reason']),
  pairing_create: new Set(['state']),
  pairing_claim: new Set(['state']),
  pairing_failure: new Set(['reason']),
  pairing_lock: new Set(['reason']),
  pairing_approve: new Set(['lifetime']),
  pairing_deny: new Set(['reason']),
  pairing_cancel: new Set(['reason']),
  pairing_expire: new Set(['reason']),
  pairing_redeem: new Set(['lifetime']),
  grant_issue: new Set(['lifetime']),
  grant_auth_failure: new Set(['reason']),
  grant_rotate: new Set(['reason']),
  grant_revoke: new Set(['reason']),
  grant_expire: new Set(['reason']),
  capability_denial: new Set(['operation']),
  rate_limiting: new Set(['bucket']),
  security_retention_run: new Set(['mode', 'outcome', 'rows']),
  'hitl.request.created': new Set([
    'boardPk',
    'hitlPk',
    'requestId',
    'actorKind',
    'interactionKind',
    'impact',
    'priorState',
    'nextState',
    'eventSequence',
    'replayed',
    'outcome',
  ]),
  'hitl.response.answered': new Set([
    'boardPk',
    'hitlPk',
    'requestId',
    'actorKind',
    'interactionKind',
    'impact',
    'priorState',
    'nextState',
    'eventSequence',
    'replayed',
    'outcome',
  ]),
  'hitl.request.cancelled': new Set([
    'boardPk',
    'hitlPk',
    'requestId',
    'actorKind',
    'interactionKind',
    'impact',
    'priorState',
    'nextState',
    'eventSequence',
    'replayed',
    'outcome',
  ]),
  'hitl.request.superseded': new Set([
    'boardPk',
    'hitlPk',
    'requestId',
    'actorKind',
    'interactionKind',
    'impact',
    'priorState',
    'nextState',
    'eventSequence',
    'replayed',
    'outcome',
  ]),
  'hitl.request.expired': new Set([
    'boardPk',
    'hitlPk',
    'requestId',
    'actorKind',
    'interactionKind',
    'impact',
    'priorState',
    'nextState',
    'eventSequence',
    'replayed',
    'outcome',
  ]),
  'hitl.response.conflict': new Set([
    'boardPk',
    'hitlPk',
    'requestId',
    'actorKind',
    'interactionKind',
    'impact',
    'priorState',
    'nextState',
    'eventSequence',
    'replayed',
    'outcome',
  ]),
  'artifact.publication.created': new Set([
    'boardPk',
    'versionPk',
    'actorKind',
    'operation',
    'status',
    'eventSequence',
    'replayed',
    'outcome',
    'capability',
    'drift',
  ]),
  'artifact.metadata.read': new Set([
    'boardPk',
    'versionPk',
    'actorKind',
    'operation',
    'status',
    'eventSequence',
    'replayed',
    'outcome',
    'capability',
    'drift',
  ]),
  'artifact.package.read': new Set([
    'boardPk',
    'versionPk',
    'actorKind',
    'operation',
    'status',
    'eventSequence',
    'replayed',
    'outcome',
    'capability',
    'drift',
  ]),
  'artifact.runtime.stopped': new Set([
    'boardPk',
    'versionPk',
    'actorKind',
    'operation',
    'status',
    'eventSequence',
    'replayed',
    'outcome',
    'capability',
    'drift',
  ]),
  'artifact.network.denied': new Set([
    'boardPk',
    'versionPk',
    'actorKind',
    'operation',
    'status',
    'eventSequence',
    'replayed',
    'outcome',
    'capability',
    'drift',
  ]),
  'artifact.usage.drift': new Set([
    'boardPk',
    'versionPk',
    'actorKind',
    'operation',
    'status',
    'eventSequence',
    'replayed',
    'outcome',
    'capability',
    'drift',
  ]),
  'artifact.integrity.failed': new Set([
    'boardPk',
    'versionPk',
    'actorKind',
    'operation',
    'status',
    'eventSequence',
    'replayed',
    'outcome',
    'capability',
    'drift',
  ]),
  password_change: new Set(['otherSessionFamiliesRevoked']),
  'invitation.issued': new Set(['boardPk', 'invitationPk', 'role']),
  'invitation.resent': new Set(['boardPk', 'invitationPk', 'role']),
  'invitation.revoked': new Set(['boardPk', 'invitationPk']),
  'invitation.accepted': new Set(['boardPk', 'invitationPk', 'role', 'replayed']),
  'membership.role.updated': new Set(['boardPk', 'membershipPk', 'role', 'capabilityEpoch']),
  'membership.removed': new Set(['boardPk', 'membershipPk', 'capabilityEpoch']),
  'share.created': new Set([
    'boardPk',
    'sharePk',
    'publicationGeneration',
    'accessGeneration',
    'recoveryId',
  ]),
  'share.republished': new Set([
    'boardPk',
    'sharePk',
    'publicationGeneration',
    'accessGeneration',
    'recoveryId',
  ]),
  'share.pin.updated': new Set([
    'boardPk',
    'sharePk',
    'publicationGeneration',
    'accessGeneration',
    'recoveryId',
  ]),
  'share.update.noop': new Set([
    'boardPk',
    'sharePk',
    'publicationGeneration',
    'accessGeneration',
    'recoveryId',
  ]),
  'share.link.rotated': new Set([
    'boardPk',
    'sharePk',
    'publicationGeneration',
    'accessGeneration',
    'recoveryId',
  ]),
  'share.revoked': new Set([
    'boardPk',
    'sharePk',
    'publicationGeneration',
    'accessGeneration',
    'recoveryId',
  ]),
  'share.archived': new Set([
    'boardPk',
    'sharePk',
    'publicationGeneration',
    'accessGeneration',
    'recoveryId',
  ]),
};

const isRecord = (value: unknown): value is Record<string, unknown> =>
  value !== null && typeof value === 'object' && !Array.isArray(value);

export const prepareAuditMetadata = (
  event: AuditEventName,
  metadata: Readonly<Record<string, unknown>>,
): Record<string, unknown> => {
  const allowed = MetadataAllowlists[event];
  for (const key of Object.keys(metadata)) {
    if (!allowed.has(key)) throw new TypeError(`audit metadata key is not allowed for ${event}`);
  }
  const redacted = redactSecrets(metadata);
  if (!isRecord(redacted)) throw new TypeError('audit metadata must serialize as an object');
  const encoded = JSON.stringify(redacted);
  if (Buffer.byteLength(encoded, 'utf8') > 4_096)
    throw new TypeError('audit metadata exceeds 4096 bytes');
  return redacted;
};
